version: "3"

services:
    nginx:
     container_name: nginx
     build: requirements/nginx/.
     env_file: .env
     ports:
     - "443:443" 		# on indique le port qui sera exposé a la machine locale
     restart: on-failure 		# Ici nous changeons, le container redémarrera uniquement en cas de crash.