version: "8.2"

services:
#mariadb
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: requirements/mariadb
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "nc", "-zv", "mariadb", "3306"]
      interval: 1s
      timeout: 5s
      retries: 18
    restart: always

#nginx
  nginx:
    image: nginx:user
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
    
# wordpress
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: requirements/wordpress
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always

### BONUS

#vsftpd
  vsftpd:
    image:  vsftpd:user
    container_name: vsftpd
    build:  requirements/bonus/vsftpd
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    secrets:
      - ftp_user
      - ftp_password
    volumes:
      - wordpress:/home/pajimene/volume
    restart:  always

#adminer
  adminer:
    image: adminer:user
    container_name: adminer
    build: requirements/bonus/adminer
    ports:
      - "4000:4000"
    networks:
      - inception
    restart: always

#redis
  redis:
    image: redis:user
    container_name: redis 
    build: requirements/bonus/redis
    networks:
      - inception
    restart: always

#lighttpd
  lighttpd:
    image: lighttpd:user
    container_name: lighttpd 
    build: requirements/bonus/lighttpd
    ports:
      - 4001:4001
    networks:
      - inception
    restart: always

#cadvisor
  cadvisor:
    image: cadvisor:user
    container_name: cadvisor
    build: requirements/bonus/cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER}/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/${USER}/data/wordpress
      o: bind
      type: none

networks:
  inception:
    name: inception

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_user:
    file: ../secrets/ftp_user.txt
  ftp_password:
    file: ../secrets/ftp_password.txt